version: "3.9"

services:
  database:
    image: postgres
    container_name: database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=na_trave_database
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
